// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CgApi
{
    public partial class TbBanco
    {
        public TbBanco()
        {
            TbContasContabeis = new HashSet<TbContasContabeis>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public string TpConta { get; set; }
        public int? FkMoeda { get; set; }

        public virtual TbMoeda FkMoedaNavigation { get; set; }
        public virtual ICollection<TbContasContabeis> TbContasContabeis { get; set; }
    }
}