// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CgApi
{
    public partial class TbCliente
    {
        public TbCliente()
        {
            TbProjeto = new HashSet<TbProjeto>();
        }

        public int Cpf { get; set; }
        public string Nome { get; set; }
        public int? Telefone { get; set; }
        public int? FkPais { get; set; }

        public virtual TbPais FkPaisNavigation { get; set; }
        public virtual ICollection<TbProjeto> TbProjeto { get; set; }
    }
}