// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CgApi
{
    public partial class TbEmpresa
    {
        public TbEmpresa()
        {
            TbFuncionario = new HashSet<TbFuncionario>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public int? Cnpj { get; set; }
        public string Endereco { get; set; }
        public int? FkContasContabeis { get; set; }

        public virtual TbContasContabeis FkContasContabeisNavigation { get; set; }
        public virtual ICollection<TbFuncionario> TbFuncionario { get; set; }
    }
}